#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: Yim's Riced ROM Project
# SPDX-License-Identifier: Apache-2.0
#
"""Generate the salami indoor auto-brightness overlay.

Stretching a lux break point by m(l) has the effect of dividing the measured
lux by m(l) before the curve lookup, so the nits targets stay untouched:

    m(l) = D                                 for l <= 1000
    m(l) = D ** (1 - log10(l / 1000))        for 1000 < l < 10000
    m(l) = 1                                 for l >= 10000
"""

import argparse
import itertools
import math
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import NamedTuple

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
UPSTREAM_SNAPSHOT = HERE / "upstream-salami-config.xml"
UPSTREAM_SOURCE = (
    "LineageOS/android_device_oneplus_salami@"
    "ba39228718c28c8aa0e46c48f89f9e8ba9450467 "
    "overlay/OPlusFrameworksResTarget/res/values/config.xml"
)
OVERLAY_CONFIG = (ROOT / "overlay" / "YrrpSalamiAutoBrightness" / "res"
                  / "values" / "config.xml")

DEFAULT_DIVISOR = 5
MAX_DIVISOR = 10  # At or above this the taper stops increasing with lux.
TAPER_START_LUX = 1000
TAPER_END_LUX = 10000
LEVELS_NAME = "config_autoBrightnessLevels"
NITS_NAME = "config_autoBrightnessDisplayValuesNits"


class Curve(NamedTuple):
    """Lux break points and the nits strings exactly as written upstream."""

    levels: list[int]
    nits: list[str]


def lux_multiplier(lux, divisor):
    """Return the stretch factor for one upstream lux break point."""
    if lux <= TAPER_START_LUX:
        return divisor
    if lux >= TAPER_END_LUX:
        return 1
    return divisor ** (1 - math.log10(lux / TAPER_START_LUX))


def check_divisor(divisor):
    """Reject a divisor outside [1, MAX_DIVISOR), including NaN and inf."""
    if not 1 <= divisor < MAX_DIVISOR:
        raise ValueError(
            f"divisor {divisor} must be at least 1 and below {MAX_DIVISOR}")


def stretch_levels(levels, divisor):
    """Stretch upstream lux break points by the log-tapered divisor.

    Raises ValueError for a divisor outside [1, MAX_DIVISOR) or when the
    rounded result would not be strictly increasing, which the framework
    rejects at boot.
    """
    check_divisor(divisor)
    stretched = [round(lux * lux_multiplier(lux, divisor)) for lux in levels]
    for low, high in itertools.pairwise(stretched):
        if low >= high:
            raise ValueError(
                f"divisor {divisor} breaks strict order: {low} >= {high}")
    return stretched


def _items(root, tag, name):
    node = root.find(f"{tag}[@name='{name}']")
    if node is None:
        raise ValueError(f"missing <{tag} name=\"{name}\">")
    return [(item.text or "").strip() for item in node.findall("item")]


def read_curve(path):
    """Read the auto-brightness lux and nits arrays from a resource file."""
    root = ET.parse(path).getroot()
    levels = [int(text) for text in _items(root, "integer-array", LEVELS_NAME)]
    nits = _items(root, "array", NITS_NAME)
    if len(levels) + 1 != len(nits):
        raise ValueError(f"{path}: need one more nits value than lux points")
    return Curve(levels, nits)


def read_divisor(rendered):
    """Return the divisor recorded in a rendered overlay's header."""
    match = re.search(r"^\s*Divisor: (\S+)$", rendered, re.MULTILINE)
    if match is None:
        raise ValueError("overlay header records no divisor")
    return _divisor(match.group(1))


def _array(tag, name, values):
    items = "".join(f"        <item>{value}</item>\n" for value in values)
    return f"    <{tag} name=\"{name}\">\n{items}    </{tag}>\n"


def render(upstream, divisor):
    """Render the overlay resource file for the given upstream curve."""
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!--\n"
        "     SPDX-FileCopyrightText: Yim's Riced ROM Project\n"
        "     SPDX-License-Identifier: Apache-2.0\n"
        "\n"
        "     Generated by tools/autobrightness/gen_overlay.py. Do not edit.\n"
        f"     Source: {UPSTREAM_SOURCE}\n"
        f"     Divisor: {divisor}\n"
        "-->\n"
        "<resources>\n"
        + _array("integer-array", LEVELS_NAME,
                 stretch_levels(upstream.levels, divisor))
        + "\n"
        + _array("array", NITS_NAME, upstream.nits)
        + "</resources>\n"
    )


def _divisor(text):
    value = float(text)
    check_divisor(value)
    return int(value) if value.is_integer() else value


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--divisor", type=_divisor, default=DEFAULT_DIVISOR,
                        help="indoor lux divisor D (default: %(default)s)")
    args = parser.parse_args()
    curve = read_curve(UPSTREAM_SNAPSHOT)
    OVERLAY_CONFIG.parent.mkdir(parents=True, exist_ok=True)
    OVERLAY_CONFIG.write_text(render(curve, args.divisor), encoding="utf-8")
    print(f"wrote {OVERLAY_CONFIG.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
